kind: project
metadata:
  name: pipe
spec:
  description: test
  params:
    label_column: label
  functions:
  - url: prep_data.py
    name: prep-data
    image: mlrun/mlrun
    handler: prep_data
    with_repo: true
  - url: hub://sklearn_classifier
    name: train
  - url: hub://test_classifier
    name: test
  - url: hub://v2_model_server
    name: serve
  workflows:
  - name: main
    path: ./kflow.py
    engine: kfp
  artifacts:
  - kind: ''
    target_path: https://s3.wasabisys.com/iguazio/data/iris/iris.data.raw.csv
    key: data
  source: ./
  subpath: ''
  origin_url: ''
  load_source_on_run: true
  desired_state: online
